[package]
name = "page-hunter"
description = "The pagination powerhouse, built with Rust"
version = "0.1.4"
authors = [
    "Juan Manuel Tamayo <jmtamayog23@gmail.com>",
]
edition = "2021"
repository = "https://github.com/jmtamayo/page-hunter"
documentation = "https://docs.rs/page-hunter"
homepage = "https://github.com/jmtamayo/page-hunter"
license-file = "../LICENSE"
readme = "../README.md"
keywords = [
    "pagination",
    "paginator",
    "page_model"
]
categories = [
    "development-tools",
]

[dependencies]
serde = { version = "1.0.203", features = ["derive"],  optional = true }
utoipa = { version = "4.2.3", optional = true}
sqlx = { version = "0.7.4", features = ["runtime-tokio", "uuid", "time", "chrono", "json", "postgres", "mysql"], optional = true }

[dev-dependencies]
tokio = { version = "1.37.0", features =["full"] }
serde_json = { version = "1.0.117" }
uuid = { version = "1.8.0" }
time = { version = "0.3.36" }

[features]
serde = ["dep:serde"]
utoipa = ["dep:utoipa", "serde"]
pg-sqlx = ["dep:sqlx"]
mysql-sqlx = ["dep:sqlx"]

[package.metadata.docs.rs]
all-features = true
