name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 0"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  Format:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: "Setup: Cargo Cache"
        uses: Swatinem/rust-cache@v2

      - name: "Step: Check Format"
        run: cargo fmt --package page-hunter --all --check --verbose

  Lints:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix: &feature_matrix
        include:
          - feature: no-features
            cargo_flags: ""
          - feature: all-features
            cargo_flags: "--all-features"
          - feature: serde
            cargo_flags: "--features serde"
          - feature: utoipa
            cargo_flags: "--features utoipa"
          - feature: sqlx
            cargo_flags: "--features sqlx"

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: "Setup: Cargo Cache"
        uses: Swatinem/rust-cache@v2

      - name: "Step: Lints"
        run: cargo clippy --package page-hunter ${{ matrix.cargo_flags }} --locked -- -D warnings

  Build:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix: *feature_matrix

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Setup: Cargo Cache"
        uses: Swatinem/rust-cache@v2

      - name: "Step: Build"
        run: cargo check --package page-hunter ${{ matrix.cargo_flags }} --locked --verbose

  Docs:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Setup: Cargo Cache"
        uses: Swatinem/rust-cache@v2

      - name: "Step: Build Doc"
        run: cargo doc --package page-hunter --all-features --document-private-items --locked --verbose

  Tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test -d test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: "Setup: Cargo Cache"
        uses: Swatinem/rust-cache@v2

      - name: "Setup: Install SQLx Cli"
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: "Setup: Postgres Database Migrations"
        env:
          MIGRATIONS_PATH: page-hunter/src/pagination/sqlx/tests/pg/migrations
          DATABASE_URL: postgres://test:docker@127.0.0.1:5432/test
        run: sqlx migrate run --source ${{ env.MIGRATIONS_PATH }}

      - name: "Step: Doc Tests"
        run: cargo test --package page-hunter --all-features --doc --locked

      - name: "Step: Unit & Integration Tests"
        env:
          DB_USER: test
          DB_PASSWORD: docker
          DB_NAME: test
          DB_HOST: 127.0.0.1
          PG_DB_PORT: 5432
        run: cargo llvm-cov --package page-hunter --all-features --locked --codecov --output-path codecov.json

      - name: "Step: Publish Results"
        uses: codecov/codecov-action@v4
        with:
          files: codecov.json
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  Security:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Step: Security Analysis"
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          log-level: warn
          manifest-path: ./page-hunter/Cargo.toml
