name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.PG_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DB_NAME }}
        ports:
            - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v2.33.22
      with:
        tool: cargo-llvm-cov

    - name: Install SQLx CLI
      run: cargo install sqlx-cli --no-default-features --features postgres

    - name: Run migrations for Postgres
      env:
        DATABASE_URL: postgres://${{ secrets.PG_DB_USER }}:${{ secrets.PG_DB_PASSWORD }}@${{ secrets.PG_DB_HOST }}:${{ secrets.PG_DB_PORT }}/${{ secrets.PG_DB_NAME }}
      run: sqlx migrate run --source page-hunter/tests/migrations/postgres 

    - name: Check project
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run tests with coverage for all features
      run: cargo llvm-cov --workspace --all-features --codecov --output-path codecov.json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.3.1
      with:
        files: codecov.json
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
